-- ============================================================
-- DRAFT — NOT APPLIED. Apply only when Josh approves the digital-services
-- release (master plan: no new production publishing or engine migration
-- without approval). On approval, copy to a timestamped file in
-- supabase/migrations/ and apply through the Supabase MCP/CLI.
--
-- digital_services_enquiries: one row per public enquiry from the
-- "Websites & digital tools" page. Owner-only data: RLS on, no policies for
-- anon/authenticated, so only the service role (server actions) can read or
-- write. The owner page reads it server-side after the owner check.
--
-- idempotency_key: generated by the form once per render; a retried submit
-- (double click, flaky signal) hits the unique index and the server returns
-- the original row instead of creating a duplicate.
-- is_test: fixture/test rows are labelled and excluded from sales numbers.
-- notified_at / notify_error: the owner alert is sent after the row is saved;
-- an alert failure is recorded here and never loses the lead.
--
-- Retention: personal details purged after 12 months, like listing_enquiries.
-- The daily /api/cron/purge-auth-events run calls the purge function below.
--
-- Rollback: drop function if exists public.purge_old_digital_services_enquiries();
--           drop table if exists public.digital_services_enquiries;
-- ============================================================

create table if not exists public.digital_services_enquiries (
  id               uuid primary key default gen_random_uuid(),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  idempotency_key  uuid not null,
  business_name    text not null check (char_length(business_name) between 2 and 120),
  contact_name     text not null check (char_length(contact_name) between 2 and 80),
  email            text not null check (char_length(email) <= 254 and email like '%@%'),
  phone            text check (phone is null or char_length(phone) <= 30),
  website          text check (website is null or char_length(website) <= 300),
  interest         text not null check (interest in ('website', 'quote_form', 'care', 'not_sure')),
  message          text not null check (char_length(message) between 10 and 2000),
  consent_at       timestamptz not null default now(),
  consent_ip       inet,
  user_agent       text,
  origin_host      text,
  status           text not null default 'new'
                     check (status in ('new', 'replied', 'qualified', 'closed', 'spam')),
  is_test          boolean not null default false,
  notified_at      timestamptz,
  notify_error     text
);

create unique index if not exists uq_ds_enquiries_idempotency
  on public.digital_services_enquiries (idempotency_key);
create index if not exists idx_ds_enquiries_created
  on public.digital_services_enquiries (created_at desc);
create index if not exists idx_ds_enquiries_ip_recent
  on public.digital_services_enquiries (consent_ip, created_at desc);

comment on table public.digital_services_enquiries is
  'Digital-services enquiries (websites/quote forms/care). Personal details with consent; owner-only via service role; purged after 12 months.';

alter table public.digital_services_enquiries enable row level security;

-- Service role only. No anon/authenticated policy on purpose: ordinary
-- marketplace admins do not get this data.
drop policy if exists "Service role manages digital services enquiries" on public.digital_services_enquiries;
create policy "Service role manages digital services enquiries"
  on public.digital_services_enquiries for all to service_role
  using (true) with check (true);

revoke all on public.digital_services_enquiries from anon, authenticated;
-- A policy only filters rows; it doesn't grant access. Grant explicitly so
-- the server keeps working even where Supabase's default grants are tightened.
grant select, insert, update, delete on public.digital_services_enquiries to service_role;

create or replace function public.purge_old_digital_services_enquiries()
returns integer
language sql
security invoker
set search_path = public
as $$
  with gone as (
    delete from public.digital_services_enquiries
    where created_at < now() - interval '12 months'
    returning 1
  )
  select count(*)::integer from gone;
$$;

revoke execute on function public.purge_old_digital_services_enquiries() from public, anon, authenticated;
grant execute on function public.purge_old_digital_services_enquiries() to service_role;
